# define third-party library paths
# CHANGE YOUR CUDA PATH IF IT IS NOT THIS
CUDA_DIR := /data5/home/vincentyao/cuda5.5
# CHANGE YOUR CUDA ARCH IF IT IS NOT THIS
CUDA_ARCH := -arch=sm_13
# CHANGE YOUR MKL PATH IF IT IS NOT THIS
MKL_DIR := /data/home/vincentyao/intel/mkl/
# CHANGE YOUR MATLAB PATH IF IT IS NOT THIS
# your mex binary should be located at $(MATLAB_DIR)/bin/mex
MATLAB_DIR := /usr/local
# PUT ALL OTHER INCLUDE AND LIB DIRECTORIES HERE
INCLUDE_DIRS :=  /usr/local/python27/include/python2.7/ \
     /usr/local/python27/lib/python2.7/site-packages/numpy/core/include \
     /data/home/vincentyao/image_classification/libthird/include/  
LIBRARY_DIRS :=  \
   /data/home/vincentyao/intel/composer_xe_2013_sp1.0.080/compiler/lib/intel64/  \
   /data/home/vincentyao/image_classification/libthird/lib 

# DEFINE THE CXX PATH
CXX=/usr/bin/g++
